### ISSUE TITLE
希望增加文件名前缀可选项。

### ISSUE THREAD

**Issue by Menzor-future** [xiaoyao-Ye/vs-quick-log#3]
对于使用多个hook的项目，我习惯于打印时加上文件名，会比较直观的看到hook调用顺序，以及在哪个文件打印后出了错。提升定位错误的效率。

**Comment by xiaoyao-Ye** [comment]
@Menzor-future 
例如当前有 A.ts B.ts 两个文件
A.ts 中的打印:
```
console.log(`( A.ts: e )===============>`, e);
```
B.ts 中的打印:
```
console.log(`( B.ts: e )===============>`, e);
```
是这个意思吗?

**Comment by xiaoyao-Ye** [comment]
@Menzor-future 
已发布 `0.2.0` 版本. 请更新插件并重启 vscode 以应用更新. 
需要手动启用 `printFilename` 选项.
有更优的建议欢迎 issues/pr (也可以直接微信找我交流: _Ghosteye)

**Comment by Menzor-future** [comment]
是这个效果，更新好快，太棒了。

**Comment by Menzor-future** [comment]
This is the effect, it updates so quickly, it’s great.
